backend:
  image: amigosnishant/backend:latest
  replicas: 1
  port: 5000
  env:
    MONGODB_URI: "mongodb://mongo-service:27017/wanderlust"

frontend:
  image: amigosnishant/frontend
  replicas: 1
  port: 5173
  nodePort: 30001
  env:
    VITE_API_PATH: "http://backend:5000"

mongo:
  image: mongo
  replicas: 1
  port: 27017

