apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-chart.fullname" . }}-backend
spec: 
  ports:
  - port: {{ .Values.backend.port }}
    protocol: TCP
  type: ClusterIP
  selector:
    app: backend

