apiVersion: v1
kind: Service
metadata: 
  name: {{ include "my-chart.fullname" . }}-frontend
spec:
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
    nodePort: {{ .Values.frontend.nodePort }}
    protocol: TCP
  type: NodePort
  selector:
    app: frontend

