apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-chart.fullname" . }}
  labels:
    database: mongodb
spec:
  replicas: {{ .Values.mongo.replicas }}
  selector:
    matchLabels:
      database: mongodb
  template:
    metadata:
      labels:
        database: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongo.image }}
          ports:
            - containerPort: {{ .Values.mongo.port }}

